management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  thymeleaf:
    cache: 'true'
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: '50'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: 'false'
      INDENT_OUTPUT: 'true'
  data:
    mongodb:
      database: local
      uri: mongodb://192.168.18.59:27017/collection?retryWrites=true&w=majority
user:
  endpoints1: http://localhost:8085
  backend: administrator
  aplicationName: bootCamp50S3
server:
  port: '8087'
