server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://192.168.18.59:8761/eureka/
  instance:
    hostname: localhost
    instance-id:
      ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: category-service
          uri: lb://funciones/api/v1
          predicates:
            - Path=/api/*
          filters:
            - StripPrefix=1


